---
name: Run VM-MANAGER-RELEASE-FLOW


on:
  issues:
    types: 
     - closed
    branches: "**"
permissions: read-all    
jobs:
  If_IssueClosed:
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ toJSON(github.event) }}
