---
name: Run VM-MANAGER-PR-MERGE-FLOW

on:
  pull_request_review:
    types: [submitted]
    branches: 
      - master
      - tmp/ci-testing
permissions: read-all    
jobs:
  if_approved:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'tmp/ci-testing'
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ toJSON(github.event) }}