---
name: Run VM-MANAGER-PR-FLOW

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: "**"
permissions: read-all
jobs:
  Trigger-Worflows:
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ toJSON(github.event) }}